---
driver:
  name: ec2
  aws_ssh_key_id: cheftrail
  region: us-east-2
  availability_zone: us-east-2c
  subnet_id: subnet-2f4c9063 # subnet-id noted from above steps
  instance_type: t2.micro # as it is free instance type
  image_id: ami-0c55b159cbfafe1f0 # image id of ubuntu
  security_group_ids: ["sg-098ac8a0420d6a4bc"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
transport:
  username: ubuntu
  ssh_key: ./cheftrail.pem
  connection_timeout: 10
  connection_retries: 5

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[maven::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
